trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'AuthDevOps'
  functionAppName: 'PyFunc265'
  resourceGroupName: 'PyFunc265_group'
  packagePath: '$(Build.ArtifactStagingDirectory)/function.zip'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'
  displayName: 'Use Python 3.11'
  
- script: |
    pip install -r requirements.txt --target="./.python_packages/lib/site-packages"
  displayName: 'Install Python dependencies'

- script: |
    zip -r $(Build.ArtifactStagingDirectory)/function.zip * .[^.]* -x "*.git*" "*.venv*" "__pycache__"
  displayName: 'Create deployment zip (from root)'

- script: |
    unzip -l $(Build.ArtifactStagingDirectory)/function.zip
  displayName: 'List zip contents (debug)'

- task: AzureFunctionApp@1
  inputs:
    azureSubscription: $(azureSubscription)
    appType: 'functionAppLinux'
    appName: $(functionAppName)
    resourceGroupName: $(resourceGroupName)
    package: $(packagePath)
    enableManagedIdentity: true
    deploymentMethod: 'runFromPackage'
