trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'AuthDevOps'
  functionAppName: 'DevOpsauth32'
  resourceGroupName: 'DevOpsauth32_group'
  packagePath: '$(System.DefaultWorkingDirectory)/src'

steps:
- task: AzureFunctionApp@1
  inputs:
    azureSubscription: $(azureSubscription)
    appType: 'functionApp'
    appName: $(functionAppName)
    resourceGroupName: $(resourceGroupName)
    package: $(packagePath)
    enableManagedIdentity: true
    deploymentMethod: 'zipDeploy'
